[platformio]
default_envs=nanoatmega328
src_dir=.
[env:nanoatmega328]
platform = atmelavr
framework = arduino
board = nanoatmega328
#upload_speed = 115200
upload_speed = 57600
lib_deps =
    robtillaart/ADS1X15@^0.5.4   
    bakercp/CRC32 @ ^2.0.0
    nicohood/PinChangeInterrupt @ ^1.2.9
    GyverLibs/EncButton @ ^3.7.0
    gyverlibs/GyverIO @ ^1.3.11
    bakercp/CRC32 @ ^2.0.0
    gyverlibs/GyverSegment @ ^1.4.7
build_flags =
    -Werror
    -Wall
    -DNDEBUG
build_src_filter=+<Lightmeter/src/**/*>

