#pragma once

#define SHOW_REL_BTN_PIN A3
#define ENCODER_BTN_PIN A1

#define ENCODER_DT_PIN 2
#define ENCODER_CLK_PIN 3
#define ENCODER_DIRECTION -1

#define ENCODER_FAST_TIMEOUT 22
#define ENCODER_FAST_FAST_TIMEOUT 6

#define DISPLAY_DIO_PIN 6
#define DISPLAY_CLK_PIN 7

#define ADC_READY_PIN 4
#define MULTIPLEXER_LOW_RESISTOR_PIN 5
#define MULTIPLEXER_LOW_RESISTOR_VALUE HIGH

#define ADC_MULTIMPLEXER_POWER_PIN 10
#define DISPLAY_POWER_PIN 12
#define DIOD_POWER_PIN 8

#define MEASURE_SOFT_CNT 5

#define AMP_R_HIGH 300
#define GAIN_AMP 24

#define AUTOSLEEP_TIME (1000ULL * 60 * 2)
